{{- if .Values.wazuh.deployment.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appIdentifier" .Values.identifier }}-cluster
  labels:
    app: {{ include "appIdentifier" .Values.identifier }}-manager-svc
  {{- with .Values.wazuh.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: cluster
      port: {{ .Values.wazuh.service.ports.wazuhInternal }}
      targetPort: {{ .Values.wazuh.service.ports.wazuhInternal }}
    - name: registration
      port: {{ .Values.wazuh.service.ports.registration }}
      targetPort: {{ .Values.wazuh.service.ports.registration }}
    - name: api
      port: {{ .Values.wazuh.service.ports.api }}
      targetPort: {{ .Values.wazuh.service.ports.api }}
  selector:
    app: {{ include "appIdentifier" .Values.identifier }}-manager-svc
  type: {{ .Values.wazuh.service.masterType }}
{{- end -}}
