{{- if .Values.indexer.deployment.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appIdentifier" .Values.identifier }}-indexer-rest
  labels:
{{ include "labels" $ | indent 4 }}
    app: {{ include "appIdentifier" .Values.identifier }}
  {{- with .Values.indexer.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: indexer-rest
      port: {{ .Values.indexer.service.httpPort }}
      targetPort: {{ .Values.indexer.service.httpPort }}
  selector:
    app: {{ include "appIdentifier" .Values.identifier }}-indexer
  type: {{ .Values.indexer.service.type }}
{{- end -}}
