{{- if .Values.wazuh.deployment.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appIdentifier" .Values.identifier }}-worker
  labels:
{{ include "labels" $ | indent 4 }}
    app: {{ include "appIdentifier" .Values.identifier }}-manager-svc
  {{- with .Values.wazuh.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: agents-events
      port: {{ .Values.wazuh.service.ports.agentEvents }}
      targetPort: {{ .Values.wazuh.service.ports.agentEvents }}
{{- if .Values.wazuh.syslog_enable }}
    - name: syslog
      port: 514
      targetPort: 514
{{- end }}
  selector:
    app: {{ include "appIdentifier" .Values.identifier }}-manager-svc
    node-type: worker
  type: {{ .Values.wazuh.service.workerType }}
{{- end -}}
