apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: wazuh
spec:
  serviceName: wazuh-indexer-service
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-indexer
  template:
    metadata:
      labels:
        app: wazuh-indexer
    spec:
      containers:
        - name: wazuh-indexer
          image: wazuh/wazuh-indexer:4.9.2
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          env:
            - name: plugins.security.disabled
              value: "true"
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
            - name: plugins.security.ssl.transport.enabled
              value: "false"
            - name: plugins.security.ssl.http.enabled
              value: "false"
  volumeClaimTemplates:
    - metadata:
        name: wazuh-indexer
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: wazuh-storage
        resources:
          requests:
            storage: 10Gi
