apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-worker
  namespace: wazuh
spec:
  serviceName: wazuh-manager-service
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager-worker
  template:
    metadata:
      labels:
        app: wazuh-manager-worker
    spec:
      containers:
        - name: wazuh-manager
          image: wazuh/wazuh-manager:4.9.2
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi
  volumeClaimTemplates:
    - metadata:
        name: wazuh-manager-worker
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: wazuh-storage
        resources:
          requests:
            storage: 50Gi
