{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "appIdentifier" .Values.identifier }}
  labels:
{{ include "labels" $ | indent 4 }}
    app: {{ include "appIdentifier" .Values.identifier }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
